FROM node:22-bookworm@sha256:0557ac14e0d45d02ed563067b82856ca5e7aa3437fa28d98d435d0ea9c3d9494a
RUN corepack enable
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile --config.engineStrict=false
RUN pnpm --filter @rakazo/www build
ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
WORKDIR /app/apps/www
CMD ["node", "server.mjs"]
