FROM node:22-bookworm@sha256:8a34c4ab3ea2c5cd194f07e317b2a8f09461d3c8b05c4e34c8ccd56d56024c4d
RUN corepack enable
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile --config.engineStrict=false
RUN pnpm --filter @rakazo/www build
ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
WORKDIR /app/apps/www
CMD ["node", "server.mjs"]
