/** Forum credentials are generated by code, stored in the vault at once and never shown to a model. */

export type RandomBytes = (length: number) => Uint8Array;

const defaultRandomBytes: RandomBytes = (length) => crypto.getRandomValues(new Uint8Array(length));

const LOWER = "abcdefghijkmnopqrstuvwxyz";
const UPPER = "ABCDEFGHJKLMNPQRSTUVWXYZ";
const DIGITS = "23456789";
const SYMBOLS = "!#%+-.:=?@_";
const PASSWORD_ALPHABET = LOWER + UPPER + DIGITS + SYMBOLS;

export const FORUM_PASSWORD_LENGTH = 22;
export const FORUM_USERNAME_MAX = 20;

/** Uniform pick from `alphabet` by rejection sampling so no character is favoured. */
function pick(alphabet: string, count: number, randomBytes: RandomBytes): string {
  const limit = 256 - (256 % alphabet.length);
  let out = "";
  while (out.length < count) {
    for (const byte of randomBytes(count * 2)) {
      if (byte >= limit) continue;
      out += alphabet[byte % alphabet.length];
      if (out.length === count) break;
    }
  }
  return out;
}

/** A password with every character class present; boards with composition rules accept it. */
export function generateForumPassword(randomBytes: RandomBytes = defaultRandomBytes): string {
  const required = [
    pick(LOWER, 1, randomBytes),
    pick(UPPER, 1, randomBytes),
    pick(DIGITS, 1, randomBytes),
    pick(SYMBOLS, 1, randomBytes),
  ];
  const rest = pick(PASSWORD_ALPHABET, FORUM_PASSWORD_LENGTH - required.length, randomBytes);
  const chars = [...required.join(""), ...rest];
  for (let index = chars.length - 1; index > 0; index -= 1) {
    const swap = (randomBytes(1)[0] ?? 0) % (index + 1);
    [chars[index], chars[swap]] = [chars[swap]!, chars[index]!];
  }
  return chars.join("");
}

function asciiSlug(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/ß/g, "ss")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

/**
 * Board username from the persona name plus two digits, e.g. `mira_sol42`. ASCII only, 3 to 20
 * characters, which every supported platform accepts.
 */
export function generateForumUsername(
  displayName: string,
  randomBytes: RandomBytes = defaultRandomBytes,
): string {
  const suffix = pick(DIGITS, 2, randomBytes);
  const base = asciiSlug(displayName) || "member";
  const trimmed = base.slice(0, FORUM_USERNAME_MAX - suffix.length).replace(/_+$/, "");
  const name = `${trimmed.length >= 1 ? trimmed : "member"}${suffix}`;
  return name.length >= 3 ? name : `member${suffix}`;
}
